//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public int ID { get; set; }
        [Display(Name = "Tài kho?n nhân viên: ")]
        public string AccountEmp { get; set; }
        [Display(Name = "M?t kh?u nhân viên: ")]
        public string PassEmp { get; set; }
        [Display(Name = "Lo?i tài kho?n: ")]
        public string CateUser { get; set; }
        [Display(Name = "Tên nhân viên: ")]
        public string NameEmp { get; set; }
        [Display(Name = "Hình ?nh nhân viên: ")]
        public string ImageEmp { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [Display(Name = "S? ?i?n tho?i nhân viên: ")]
        public string PhoneEmp { get; set; }
        [Display(Name = "Email nhân viên: ")]
        public string EmailEmp { get; set; }
        [Display(Name = "Ngày sinh nhân viên: ")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateOfBirthEmp { get; set; }
        [Display(Name = "??a ch? nhân viên: ")]
        public string AddressEmp { get; set; }
        [Display(Name = "Gi?i tính: ")]
        public Nullable<bool> SexEmp { get; set; }


        public virtual CategoryUser CategoryUser { get; set; }
    }
}
