//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.Mvc;

    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.DetailBills = new HashSet<DetailBill>();
            ImageFood = "~/Content/images/Avatar.jpg";
        }
        [Display(Name = "Mã món ăn")]
        public string IDFood { get; set; }
        [Display(Name = "Tên món ăn:")]
        public string NameFood { get; set; }
        [Display(Name = "Hình ảnh món ăn:")]
        public string ImageFood { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [Display(Name = "Giá món ?n: ")]
        public Nullable<double> PriceFood { get; set; }
        [Display(Name = "Tr?ng thái món ?n: ")]
        public Nullable<bool> StatusFood { get; set; }
        [Display(Name = "Lo?i món ?n:")]
        public string CateFood { get; set; }
        [Display(Name = "S? l??ng món ?n:")]
        public Nullable<int> QuantityFood { get; set; }
        [Display(Name = "Mô t? món ?n:")]
        [AllowHtml]
        public string DesFood { get; set; }
        public string Trending { get; set; }
    
        public virtual CategoryFood CategoryFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
    }
    public enum Gender
    {
        NewFood, BestSeller, Normal
    }
}
